import json
from copy import deepcopy
from pathlib import Path

from ui.input_worksheet import build_patient_from_inputs


DEMO_CASES = (
    ("Low-risk clean prevention", "healthy_low_risk_prevention"),
    ("Borderline ASCVD discussion", "borderline_ascvd_discussion"),
    ("Low 10-year / elevated 30-year risk", "low_10y_elevated_30y"),
    ("Younger patient with premature family history", "younger_strong_family_history"),
    ("Prediabetes / insulin resistance", "prediabetes_insulin_resistance"),
    ("High ApoB discordance", "high_apob_discordance"),
    ("LDL-C high, ApoB missing", "ldl_high_apob_missing"),
    ("LDL-C >=190 severe hypercholesterolemia", "ldl_severe_hypercholesterolemia_demo"),
    ("Elevated Lp(a)", "elevated_lpa"),
    ("Hypertriglyceridemia / insulin resistance", "hypertriglyceridemia_insulin_resistance"),
    ("CAC 0 ambiguity resolution", "cac_zero_ambiguity_resolution"),
    ("CAC 1-99 plaque present", "cac_1_99_plaque_present"),
    ("CAC >=100 treatment clarification", "cac_100_high_plaque_burden"),
    ("CAC >=300 high plaque burden", "cac_300_high_plaque_burden"),
    ("Incidental CAC on CT", "incidental_cac_on_ct"),
    ("Breast arterial calcification", "breast_arterial_calcification_demo"),
    ("Type 2 diabetes without kidney disease", "diabetes_without_kidney_disease"),
    ("Type 2 diabetes with albuminuria", "diabetes_ckm_stage"),
    ("CKD G2A2 albuminuria", "ckd_albuminuria"),
    ("CKD G3aA2", "ckd_g3a_a2"),
    ("Higher albuminuria / SGLT2 consideration", "higher_albuminuria_sglt2_consideration"),
    ("On-treatment above-target lipids", "on_treatment_above_target_lipids"),
    ("High-intensity statin, add-on discussion", "high_intensity_add_on_discussion"),
    ("Severe secondary prevention", "severe_secondary_prevention"),
    ("Statin intolerance", "statin_intolerance_demo"),
    ("BP treated but above kidney goal", "bp_treated_above_kidney_goal"),
    ("ACEi/ARB with persistent albuminuria", "ace_arb_persistent_albuminuria"),
    ("Rheumatoid arthritis risk enhancer", "rheumatoid_arthritis_risk_enhancer"),
    ("South Asian ancestry context", "south_asian_ancestry_context"),
    ("Active smoker prevention visit", "active_smoker_prevention"),
    ("Cancer survivor context", "cancer_survivor_context"),
    ("Multiple enhancers, missing ApoB/Lp(a)", "multiple_enhancers_missing_apob_lpa"),
)


DEMO_PATIENTS = {
    "healthy_low_risk_prevention": {
        "age": 34,
        "sex": "female",
        "height_in": 65,
        "weight_lb": 132,
        "bmi": 22.0,
        "sbp": 108,
        "dbp": 68,
        "bp_treated": False,
        "tc": 168,
        "ldl_c": 88,
        "hdl_c": 62,
        "triglycerides": 88,
        "apob": 70,
        "lp_a_value": 18,
        "lp_a_unit": "nmol/L",
        "a1c": 5.2,
        "diabetes": False,
        "egfr": 105,
        "creatinine": 0.78,
        "uacr": 4,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "none",
    },
    "obesity_metabolic_syndrome": {
        "age": 48,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 235,
        "bmi": 33.7,
        "sbp": 136,
        "dbp": 86,
        "bp_treated": False,
        "tc": 212,
        "ldl_c": 132,
        "hdl_c": 39,
        "triglycerides": 205,
        "apob": 108,
        "lp_a_value": 36,
        "lp_a_unit": "nmol/L",
        "a1c": 5.6,
        "diabetes": False,
        "egfr": 92,
        "creatinine": 1.0,
        "uacr": None,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "osa": True,
        "masld": True,
        "medications_raw": "none",
    },
    "borderline_ascvd_discussion": {
        "age": 56,
        "sex": "male",
        "height_in": 69,
        "weight_lb": 196,
        "bmi": 28.9,
        "sbp": 132,
        "dbp": 80,
        "bp_treated": False,
        "tc": 208,
        "ldl_c": 134,
        "hdl_c": 46,
        "triglycerides": 142,
        "apob": 102,
        "lp_a_value": 42,
        "lp_a_unit": "nmol/L",
        "a1c": 5.5,
        "diabetes": False,
        "egfr": 88,
        "creatinine": 0.98,
        "uacr": 8,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "prevent_10y_ascvd": 5.8,
        "prevent_30y_ascvd": 18.6,
        "medications_raw": "none",
    },
    "low_10y_elevated_30y": {
        "age": 43,
        "sex": "female",
        "height_in": 66,
        "weight_lb": 174,
        "bmi": 28.1,
        "sbp": 124,
        "dbp": 76,
        "bp_treated": False,
        "tc": 224,
        "ldl_c": 146,
        "hdl_c": 50,
        "triglycerides": 156,
        "apob": 122,
        "lp_a_value": None,
        "lp_a_unit": "nmol/L",
        "a1c": 5.8,
        "diabetes": False,
        "egfr": 96,
        "creatinine": 0.82,
        "uacr": 7,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "prevent_10y_ascvd": 3.4,
        "prevent_30y_ascvd": 24.0,
        "medications_raw": "none",
    },
    "prediabetes_insulin_resistance": {
        "age": 52,
        "sex": "female",
        "height_in": 64,
        "weight_lb": 184,
        "bmi": 31.6,
        "sbp": 128,
        "dbp": 78,
        "bp_treated": False,
        "tc": 198,
        "ldl_c": 122,
        "hdl_c": 46,
        "triglycerides": 168,
        "apob": 92,
        "lp_a_value": 40,
        "lp_a_unit": "nmol/L",
        "a1c": 6.1,
        "diabetes": False,
        "egfr": 88,
        "creatinine": 0.86,
        "uacr": 12,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "gestational_diabetes": True,
        "medications_raw": "vitamin D",
    },
    "high_apob_discordance": {
        "age": 55,
        "sex": "male",
        "height_in": 69,
        "weight_lb": 190,
        "bmi": 28.1,
        "sbp": 126,
        "dbp": 76,
        "bp_treated": False,
        "tc": 190,
        "ldl_c": 108,
        "hdl_c": 48,
        "triglycerides": 170,
        "apob": 125,
        "lp_a_value": 30,
        "lp_a_unit": "nmol/L",
        "a1c": 5.5,
        "diabetes": False,
        "egfr": 90,
        "creatinine": 0.98,
        "uacr": 8,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": True,
        "family_history_relationship": "father",
        "family_history_event_type": "MI",
        "family_history_age_at_event": 49,
        "medications_raw": "none",
    },
    "ldl_high_apob_missing": {
        "age": 51,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 202,
        "bmi": 29.0,
        "sbp": 130,
        "dbp": 78,
        "bp_treated": False,
        "tc": 245,
        "ldl_c": 172,
        "hdl_c": 45,
        "triglycerides": 165,
        "apob": None,
        "lp_a_value": None,
        "lp_a_unit": "nmol/L",
        "a1c": 5.6,
        "diabetes": False,
        "egfr": 94,
        "creatinine": 0.96,
        "uacr": 9,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "prevent_10y_ascvd": 4.6,
        "prevent_30y_ascvd": 28.0,
        "medications_raw": "none",
    },
    "ldl_severe_hypercholesterolemia_demo": {
        "age": 45,
        "sex": "male",
        "height_in": 71,
        "weight_lb": 188,
        "bmi": 26.2,
        "sbp": 122,
        "dbp": 74,
        "bp_treated": False,
        "tc": 292,
        "ldl_c": 212,
        "hdl_c": 48,
        "triglycerides": 155,
        "apob": None,
        "lp_a_value": 58,
        "lp_a_unit": "nmol/L",
        "a1c": 5.4,
        "diabetes": False,
        "egfr": 98,
        "creatinine": 0.92,
        "uacr": 6,
        "cac": 0,
        "smoker": False,
        "family_history_premature_ascvd": True,
        "family_history_relationship": "father",
        "family_history_event_type": "MI",
        "family_history_age_at_event": 52,
        "suspected_fh_hefh": True,
        "prevent_10y_ascvd": 2.8,
        "prevent_30y_ascvd": 22.0,
        "medications_raw": "none",
    },
    "elevated_lpa": {
        "age": 46,
        "sex": "female",
        "height_in": 66,
        "weight_lb": 150,
        "bmi": 24.2,
        "sbp": 118,
        "dbp": 72,
        "bp_treated": False,
        "tc": 190,
        "ldl_c": 124,
        "hdl_c": 56,
        "triglycerides": 90,
        "apob": 86,
        "lp_a_value": 188,
        "lp_a_unit": "nmol/L",
        "a1c": 5.3,
        "diabetes": False,
        "egfr": 98,
        "creatinine": 0.76,
        "uacr": 5,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "preeclampsia": True,
        "medications_raw": "levothyroxine",
    },
    "cac_zero_ambiguity_resolution": {
        "age": 58,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 207,
        "bmi": 29.7,
        "sbp": 134,
        "dbp": 82,
        "bp_treated": True,
        "tc": 215,
        "ldl_c": 142,
        "hdl_c": 44,
        "triglycerides": 146,
        "apob": 105,
        "lp_a_value": None,
        "lp_a_unit": "nmol/L",
        "a1c": 5.7,
        "diabetes": False,
        "egfr": 86,
        "creatinine": 0.94,
        "uacr": 10,
        "cac": 0,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "lisinopril 10 mg daily",
        "ace_arb": True,
    },
    "cac_1_99_plaque_present": {
        "age": 62,
        "sex": "female",
        "height_in": 64,
        "weight_lb": 172,
        "bmi": 29.5,
        "sbp": 132,
        "dbp": 78,
        "bp_treated": True,
        "tc": 205,
        "ldl_c": 128,
        "hdl_c": 52,
        "triglycerides": 125,
        "apob": 95,
        "lp_a_value": 82,
        "lp_a_unit": "nmol/L",
        "a1c": 5.8,
        "diabetes": False,
        "egfr": 82,
        "creatinine": 0.88,
        "uacr": 9,
        "cac": 38,
        "cac_percentile": 82,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "amlodipine 5 mg daily; hydrochlorothiazide 12.5 mg daily",
    },
    "cac_100_high_plaque_burden": {
        "age": 61,
        "sex": "female",
        "height_in": 65,
        "weight_lb": 176,
        "bmi": 29.3,
        "sbp": 138,
        "dbp": 84,
        "bp_treated": True,
        "tc": 218,
        "ldl_c": 124,
        "hdl_c": 56,
        "triglycerides": 190,
        "apob": 112,
        "lp_a_value": 238,
        "lp_a_unit": "nmol/L",
        "a1c": 5.9,
        "diabetes": False,
        "egfr": 78,
        "creatinine": 0.9,
        "uacr": 14,
        "cac": 145,
        "cac_percentile": 91,
        "smoker": False,
        "family_history_premature_ascvd": True,
        "family_history_relationship": "father",
        "family_history_event_type": "MI",
        "family_history_age_at_event": 54,
        "medications_raw": "losartan 50 mg daily",
        "ace_arb": True,
    },
    "hypertriglyceridemia_insulin_resistance": {
        "age": 50,
        "sex": "male",
        "height_in": 69,
        "weight_lb": 228,
        "bmi": 33.7,
        "sbp": 134,
        "dbp": 84,
        "bp_treated": False,
        "tc": 232,
        "ldl_c": 118,
        "hdl_c": 34,
        "triglycerides": 360,
        "apob": 118,
        "lp_a_value": 28,
        "lp_a_unit": "nmol/L",
        "a1c": 6.2,
        "diabetes": False,
        "egfr": 88,
        "creatinine": 1.05,
        "uacr": 16,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "osa": True,
        "masld": True,
        "prevent_10y_ascvd": 6.2,
        "prevent_30y_ascvd": 30.0,
        "medications_raw": "none",
    },
    "cac_300_high_plaque_burden": {
        "age": 63,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 210,
        "bmi": 30.1,
        "sbp": 136,
        "dbp": 82,
        "bp_treated": True,
        "tc": 210,
        "ldl_c": 126,
        "hdl_c": 42,
        "triglycerides": 180,
        "apob": 110,
        "lp_a_value": 160,
        "lp_a_unit": "nmol/L",
        "a1c": 6.0,
        "diabetes": False,
        "egfr": 74,
        "creatinine": 1.05,
        "uacr": 18,
        "cac": 350,
        "cac_percentile": 88,
        "smoker": False,
        "family_history_premature_ascvd": True,
        "family_history_relationship": "brother",
        "family_history_event_type": "MI",
        "family_history_age_at_event": 50,
        "lipid_lowering": False,
        "medications_raw": "losartan 50 mg daily",
        "ace_arb": True,
    },
    "incidental_cac_on_ct": {
        "age": 66,
        "sex": "female",
        "height_in": 64,
        "weight_lb": 168,
        "bmi": 28.8,
        "sbp": 130,
        "dbp": 76,
        "bp_treated": True,
        "tc": 198,
        "ldl_c": 118,
        "hdl_c": 52,
        "triglycerides": 142,
        "apob": 96,
        "lp_a_value": 42,
        "lp_a_unit": "nmol/L",
        "a1c": 5.7,
        "diabetes": False,
        "egfr": 78,
        "creatinine": 0.9,
        "uacr": 11,
        "cac": None,
        "cac_not_done": False,
        "incidental_cac": True,
        "incidental_cac_severity": "moderate",
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "amlodipine 5 mg daily",
    },
    "breast_arterial_calcification_demo": {
        "age": 59,
        "sex": "female",
        "height_in": 65,
        "weight_lb": 166,
        "bmi": 27.6,
        "sbp": 126,
        "dbp": 78,
        "bp_treated": False,
        "tc": 206,
        "ldl_c": 132,
        "hdl_c": 54,
        "triglycerides": 132,
        "apob": 98,
        "lp_a_value": 88,
        "lp_a_unit": "nmol/L",
        "a1c": 5.6,
        "diabetes": False,
        "egfr": 84,
        "creatinine": 0.86,
        "uacr": 9,
        "cac_not_done": True,
        "breast_arterial_calcification": "present",
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "none",
    },
    "ckd_albuminuria": {
        "age": 57,
        "sex": "male",
        "height_in": 68,
        "weight_lb": 204,
        "bmi": 31.0,
        "sbp": 142,
        "dbp": 86,
        "bp_treated": True,
        "tc": 202,
        "ldl_c": 126,
        "hdl_c": 46,
        "triglycerides": 150,
        "apob": 96,
        "lp_a_value": 65,
        "lp_a_unit": "nmol/L",
        "a1c": 6.0,
        "diabetes": False,
        "egfr": 64,
        "creatinine": 1.25,
        "uacr": 48,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "losartan 100 mg daily; chlorthalidone 12.5 mg daily",
        "ace_arb": True,
    },
    "diabetes_ckm_stage": {
        "age": 60,
        "sex": "female",
        "height_in": 63,
        "weight_lb": 186,
        "bmi": 32.9,
        "sbp": 136,
        "dbp": 80,
        "bp_treated": True,
        "tc": 210,
        "ldl_c": 132,
        "hdl_c": 43,
        "triglycerides": 176,
        "apob": 110,
        "lp_a_value": 42,
        "lp_a_unit": "nmol/L",
        "a1c": 7.4,
        "diabetes": True,
        "diabetes_duration_years": 8,
        "egfr": 52,
        "creatinine": 1.15,
        "uacr": 210,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "metformin 1000 mg twice daily; lisinopril 20 mg daily",
        "dm_meds_raw": "metformin",
        "ace_arb": True,
    },
    "diabetes_without_kidney_disease": {
        "age": 54,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 218,
        "bmi": 31.3,
        "sbp": 128,
        "dbp": 78,
        "bp_treated": False,
        "tc": 204,
        "ldl_c": 122,
        "hdl_c": 44,
        "triglycerides": 190,
        "apob": 104,
        "lp_a_value": 30,
        "lp_a_unit": "nmol/L",
        "a1c": 7.1,
        "diabetes": True,
        "diabetes_duration_years": 3,
        "egfr": 92,
        "creatinine": 0.94,
        "uacr": 8,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "metformin 500 mg twice daily",
        "dm_meds_raw": "metformin",
    },
    "ckd_g3a_a2": {
        "age": 64,
        "sex": "female",
        "height_in": 63,
        "weight_lb": 176,
        "bmi": 31.2,
        "sbp": 138,
        "dbp": 78,
        "bp_treated": True,
        "tc": 196,
        "ldl_c": 118,
        "hdl_c": 50,
        "triglycerides": 142,
        "apob": 94,
        "lp_a_value": 54,
        "lp_a_unit": "nmol/L",
        "a1c": 5.8,
        "diabetes": False,
        "egfr": 55,
        "creatinine": 1.18,
        "uacr": 72,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "losartan 50 mg daily",
        "ace_arb": True,
    },
    "higher_albuminuria_sglt2_consideration": {
        "age": 58,
        "sex": "male",
        "height_in": 69,
        "weight_lb": 214,
        "bmi": 31.6,
        "sbp": 136,
        "dbp": 82,
        "bp_treated": True,
        "tc": 206,
        "ldl_c": 128,
        "hdl_c": 44,
        "triglycerides": 170,
        "apob": 106,
        "lp_a_value": 40,
        "lp_a_unit": "nmol/L",
        "a1c": 6.8,
        "diabetes": True,
        "diabetes_duration_years": 4,
        "egfr": 48,
        "creatinine": 1.42,
        "uacr": 320,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "metformin; lisinopril 20 mg daily",
        "dm_meds_raw": "metformin",
        "ace_arb": True,
        "sglt2": False,
    },
    "on_treatment_above_target_lipids": {
        "age": 61,
        "sex": "female",
        "height_in": 65,
        "weight_lb": 173,
        "bmi": 28.8,
        "sbp": 124,
        "dbp": 76,
        "bp_treated": True,
        "tc": 218,
        "ldl_c": 124,
        "hdl_c": 56,
        "triglycerides": 190,
        "apob": 112,
        "lp_a_value": 238,
        "lp_a_unit": "nmol/L",
        "a1c": 5.8,
        "diabetes": False,
        "egfr": 76,
        "creatinine": 0.92,
        "uacr": 11,
        "cac": 145,
        "cac_percentile": 78,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "lipid_lowering": True,
        "statin_intensity": "moderate",
        "statin_intolerance": True,
        "medications_raw": "pravastatin 40 mg daily; ezetimibe 10 mg daily; prior atorvastatin and rosuvastatin myalgias",
    },
    "high_intensity_add_on_discussion": {
        "age": 67,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 202,
        "bmi": 29.0,
        "sbp": 126,
        "dbp": 74,
        "bp_treated": True,
        "tc": 188,
        "ldl_c": 104,
        "hdl_c": 46,
        "triglycerides": 190,
        "apob": 102,
        "lp_a_value": 210,
        "lp_a_unit": "nmol/L",
        "a1c": 5.9,
        "diabetes": False,
        "egfr": 70,
        "creatinine": 1.02,
        "uacr": 12,
        "cac": 420,
        "cac_percentile": 90,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "lipid_lowering": True,
        "statin_intensity": "high",
        "medications_raw": "rosuvastatin 20 mg daily; losartan 50 mg daily",
        "ace_arb": True,
    },
    "severe_secondary_prevention": {
        "age": 66,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 218,
        "bmi": 31.3,
        "sbp": 138,
        "dbp": 82,
        "bp_treated": True,
        "tc": 312,
        "ldl_c": 205,
        "hdl_c": 38,
        "triglycerides": 340,
        "apob": 156,
        "lp_a_value": 225,
        "lp_a_unit": "nmol/L",
        "a1c": 7.8,
        "diabetes": True,
        "diabetes_duration_years": 12,
        "egfr": 55,
        "creatinine": 1.36,
        "uacr": 86,
        "cac": 5000,
        "clinical_ascvd": True,
        "clinical_ascvd_context": "prior MI with PCI; ischemic stroke; PAD",
        "suspected_fh_hefh": True,
        "smoker": False,
        "hypertension": True,
        "family_history_premature_ascvd": True,
        "family_history_relationship": "father",
        "family_history_event_type": "MI",
        "family_history_age_at_event": 48,
        "family_history_summary": "Father MI age 48",
        "lipid_lowering": True,
        "statin_intensity": "high",
        "medications_raw": "atorvastatin 80 mg daily; metformin; lisinopril 20 mg daily; aspirin",
        "dm_meds_raw": "metformin",
        "ace_arb": True,
        "sglt2": False,
    },
    "statin_intolerance_demo": {
        "age": 60,
        "sex": "female",
        "height_in": 64,
        "weight_lb": 170,
        "bmi": 29.2,
        "sbp": 128,
        "dbp": 76,
        "bp_treated": True,
        "tc": 224,
        "ldl_c": 146,
        "hdl_c": 52,
        "triglycerides": 130,
        "apob": 116,
        "lp_a_value": 120,
        "lp_a_unit": "nmol/L",
        "a1c": 5.7,
        "diabetes": False,
        "egfr": 82,
        "creatinine": 0.88,
        "uacr": 10,
        "cac": 90,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "lipid_lowering": True,
        "statin_intensity": "low",
        "statin_intolerance": True,
        "medications_raw": "pravastatin 10 mg daily; prior atorvastatin myalgias; amlodipine 5 mg daily",
    },
    "bp_treated_above_kidney_goal": {
        "age": 62,
        "sex": "male",
        "height_in": 68,
        "weight_lb": 208,
        "bmi": 31.6,
        "sbp": 148,
        "dbp": 86,
        "bp_treated": True,
        "tc": 198,
        "ldl_c": 118,
        "hdl_c": 46,
        "triglycerides": 170,
        "apob": 98,
        "lp_a_value": 34,
        "lp_a_unit": "nmol/L",
        "a1c": 6.1,
        "diabetes": False,
        "egfr": 62,
        "creatinine": 1.24,
        "uacr": 86,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "losartan 50 mg daily; amlodipine 5 mg daily",
        "ace_arb": True,
    },
    "ace_arb_persistent_albuminuria": {
        "age": 59,
        "sex": "female",
        "height_in": 65,
        "weight_lb": 184,
        "bmi": 30.6,
        "sbp": 132,
        "dbp": 78,
        "bp_treated": True,
        "tc": 202,
        "ldl_c": 124,
        "hdl_c": 48,
        "triglycerides": 150,
        "apob": 100,
        "lp_a_value": 36,
        "lp_a_unit": "nmol/L",
        "a1c": 6.6,
        "diabetes": True,
        "diabetes_duration_years": 5,
        "egfr": 58,
        "creatinine": 1.05,
        "uacr": 180,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "metformin; losartan 100 mg daily",
        "dm_meds_raw": "metformin",
        "ace_arb": True,
        "sglt2": False,
    },
    "sparse_realistic_pcp_intake": {
        "age": 49,
        "sex": "male",
        "height_in": 71,
        "weight_lb": 198,
        "bmi": 27.6,
        "sbp": 128,
        "dbp": 80,
        "bp_treated": False,
        "tc": 214,
        "ldl_c": 136,
        "hdl_c": 45,
        "triglycerides": 165,
        "a1c": None,
        "diabetes": False,
        "egfr": 96,
        "creatinine": 1.0,
        "uacr": None,
        "apob": None,
        "lp_a_value": None,
        "lp_a_unit": "nmol/L",
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "none",
    },
    "younger_strong_family_history": {
        "age": 38,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 205,
        "bmi": 29.4,
        "sbp": 124,
        "dbp": 78,
        "bp_treated": False,
        "tc": 236,
        "ldl_c": 164,
        "hdl_c": 48,
        "triglycerides": 186,
        "apob": 118,
        "lp_a_value": 96,
        "lp_a_unit": "nmol/L",
        "a1c": 5.9,
        "diabetes": False,
        "egfr": 100,
        "creatinine": 0.9,
        "uacr": 9,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": True,
        "family_history_relationship": "father",
        "family_history_event_type": "MI",
        "family_history_age_at_event": 49,
        "medications_raw": "none",
    },
    "older_multiple_treated_risk_factors": {
        "age": 72,
        "sex": "female",
        "height_in": 62,
        "weight_lb": 178,
        "bmi": 32.6,
        "sbp": 132,
        "dbp": 74,
        "bp_treated": True,
        "tc": 176,
        "ldl_c": 92,
        "hdl_c": 50,
        "triglycerides": 170,
        "apob": 88,
        "lp_a_value": 30,
        "lp_a_unit": "nmol/L",
        "a1c": 7.0,
        "diabetes": True,
        "diabetes_duration_years": 6,
        "egfr": 68,
        "creatinine": 0.98,
        "uacr": 22,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "lipid_lowering": True,
        "statin_intensity": "moderate",
        "sglt2": True,
        "ace_arb": True,
        "medications_raw": "atorvastatin 20 mg daily; metformin; empagliflozin; losartan 50 mg daily",
        "dm_meds_raw": "metformin; empagliflozin",
    },
    "rheumatoid_arthritis_risk_enhancer": {
        "age": 53,
        "sex": "female",
        "height_in": 64,
        "weight_lb": 162,
        "bmi": 27.8,
        "sbp": 124,
        "dbp": 76,
        "bp_treated": False,
        "tc": 206,
        "ldl_c": 132,
        "hdl_c": 56,
        "triglycerides": 90,
        "apob": 94,
        "lp_a_value": 48,
        "lp_a_unit": "nmol/L",
        "a1c": 5.4,
        "diabetes": False,
        "egfr": 86,
        "creatinine": 0.82,
        "uacr": 7,
        "cac_not_done": True,
        "smoker": False,
        "rheumatoid_arthritis": True,
        "family_history_premature_ascvd": False,
        "prevent_10y_ascvd": 4.2,
        "prevent_30y_ascvd": 18.5,
        "medications_raw": "methotrexate; folic acid",
    },
    "south_asian_ancestry_context": {
        "age": 47,
        "sex": "male",
        "height_in": 68,
        "weight_lb": 178,
        "bmi": 27.1,
        "sbp": 126,
        "dbp": 78,
        "bp_treated": False,
        "tc": 212,
        "ldl_c": 138,
        "hdl_c": 44,
        "triglycerides": 174,
        "apob": 108,
        "lp_a_value": 68,
        "lp_a_unit": "nmol/L",
        "a1c": 5.8,
        "diabetes": False,
        "egfr": 94,
        "creatinine": 0.9,
        "uacr": 8,
        "cac_not_done": True,
        "smoker": False,
        "south_asian_ancestry": True,
        "family_history_premature_ascvd": False,
        "prevent_10y_ascvd": 3.8,
        "prevent_30y_ascvd": 22.0,
        "medications_raw": "none",
    },
    "active_smoker_prevention": {
        "age": 50,
        "sex": "female",
        "height_in": 65,
        "weight_lb": 156,
        "bmi": 26.0,
        "sbp": 130,
        "dbp": 78,
        "bp_treated": False,
        "tc": 198,
        "ldl_c": 124,
        "hdl_c": 50,
        "triglycerides": 120,
        "apob": 92,
        "lp_a_value": 30,
        "lp_a_unit": "nmol/L",
        "a1c": 5.5,
        "diabetes": False,
        "egfr": 90,
        "creatinine": 0.82,
        "uacr": 7,
        "cac_not_done": True,
        "smoker": True,
        "family_history_premature_ascvd": False,
        "prevent_10y_ascvd": 6.8,
        "prevent_30y_ascvd": 26.0,
        "medications_raw": "nicotine replacement discussed; no chronic medications",
    },
    "cancer_survivor_context": {
        "age": 58,
        "sex": "female",
        "height_in": 66,
        "weight_lb": 172,
        "bmi": 27.8,
        "sbp": 128,
        "dbp": 78,
        "bp_treated": False,
        "tc": 210,
        "ldl_c": 136,
        "hdl_c": 52,
        "triglycerides": 110,
        "apob": 98,
        "lp_a_value": 44,
        "lp_a_unit": "nmol/L",
        "a1c": 5.6,
        "diabetes": False,
        "egfr": 82,
        "creatinine": 0.88,
        "uacr": 8,
        "cac_not_done": True,
        "smoker": False,
        "cancer_survivor": True,
        "cancer_life_expectancy_gt_2y": True,
        "family_history_premature_ascvd": False,
        "prevent_10y_ascvd": 5.2,
        "prevent_30y_ascvd": 19.0,
        "medications_raw": "anastrozole; calcium/vitamin D",
    },
    "multiple_enhancers_missing_apob_lpa": {
        "age": 52,
        "sex": "female",
        "height_in": 63,
        "weight_lb": 182,
        "bmi": 32.2,
        "sbp": 134,
        "dbp": 82,
        "bp_treated": False,
        "tc": 222,
        "ldl_c": 142,
        "hdl_c": 44,
        "triglycerides": 182,
        "apob": None,
        "lp_a_value": None,
        "lp_a_unit": "nmol/L",
        "a1c": 6.0,
        "diabetes": False,
        "egfr": 86,
        "creatinine": 0.88,
        "uacr": None,
        "cac_not_done": True,
        "smoker": False,
        "preeclampsia": True,
        "osa": True,
        "masld": True,
        "family_history_premature_ascvd": True,
        "family_history_relationship": "mother",
        "family_history_event_type": "stroke",
        "family_history_age_at_event": 62,
        "prevent_10y_ascvd": 4.9,
        "prevent_30y_ascvd": 27.0,
        "medications_raw": "none",
    },
}


DEMO_CASE_DESCRIPTIONS = {
    "healthy_low_risk_prevention": (
        "Clean baseline prevention visit with low ASCVD risk and complete reassuring data."
    ),
    "borderline_ascvd_discussion": (
        "Borderline 10-year ASCVD risk with modest ApoB burden shows shared-decision statin discussion."
    ),
    "low_10y_elevated_30y": (
        "Low short-term ASCVD risk but elevated longer-term risk makes prevention worth discussing."
    ),
    "obesity_metabolic_syndrome": (
        "Obesity, OSA/metabolic fatty liver context, and triglyceride burden with advanced clarifiers still open."
    ),
    "prediabetes_insulin_resistance": (
        "Prediabetes and insulin-resistance pattern with reproductive history context."
    ),
    "high_apob_discordance": (
        "Low 10-year risk, but elevated ApoB and premature family history make earlier lipid-lowering reasonable to discuss."
    ),
    "ldl_high_apob_missing": (
        "LDL-C is high while ApoB is missing, showing how RCCKM prompts particle-burden clarification."
    ),
    "ldl_severe_hypercholesterolemia_demo": (
        "LDL-C >=190 remains treatment-forward even with CAC 0 and low calculated short-term risk."
    ),
    "elevated_lpa": (
        "Low near-term risk with elevated Lp(a) and reproductive risk context."
    ),
    "hypertriglyceridemia_insulin_resistance": (
        "Triglycerides, obesity, prediabetes, OSA, and metabolic fatty liver disease show insulin-resistance burden."
    ),
    "cac_zero_ambiguity_resolution": (
        "CAC 0 helps frame plaque burden while cardiometabolic signals remain visible."
    ),
    "cac_1_99_plaque_present": (
        "Mild measured coronary calcium demonstrates the plaque-present pathway."
    ),
    "cac_100_high_plaque_burden": (
        "CAC >=100 clarifies plaque presence and strengthens lipid-treatment intensity."
    ),
    "cac_300_high_plaque_burden": (
        "CAC 350 demonstrates high plaque burden where plaque status dominates risk interpretation."
    ),
    "incidental_cac_on_ct": (
        "Qualitative incidental CAC on nongated CT creates plaque context without an Agatston score."
    ),
    "breast_arterial_calcification_demo": (
        "Breast arterial calcification is captured as a non-coronary vascular risk marker."
    ),
    "ckd_albuminuria": (
        "Albuminuria and treated BP show early kidney-risk interpretation."
    ),
    "diabetes_ckm_stage": (
        "Diabetes with CKM/kidney involvement and treatment-forward prevention needs."
    ),
    "diabetes_without_kidney_disease": (
        "Type 2 diabetes with preserved kidney markers shows diabetes-driven prevention without CKD."
    ),
    "ckd_g3a_a2": (
        "Reduced eGFR with albuminuria demonstrates CKD G3aA2 risk integration."
    ),
    "higher_albuminuria_sglt2_consideration": (
        "Higher albuminuria with diabetes demonstrates kidney-protective SGLT2 consideration."
    ),
    "on_treatment_above_target_lipids": (
        "Already on lipid therapy but above CAC-driven targets with prior statin intolerance."
    ),
    "high_intensity_add_on_discussion": (
        "Already on high-intensity statin with CAC and Lp(a) shows add-on therapy consideration."
    ),
    "severe_secondary_prevention": (
        "Established ASCVD with diabetes, CKD, severe LDL-C/ApoB burden, Lp(a), and CAC context shows very-high-risk secondary-prevention targets."
    ),
    "statin_intolerance_demo": (
        "Statin intolerance with plaque and ApoB burden shows medication-status-aware lipid planning."
    ),
    "bp_treated_above_kidney_goal": (
        "Treated BP remains above kidney goal in albuminuria, highlighting BP and kidney protection."
    ),
    "ace_arb_persistent_albuminuria": (
        "ACEi/ARB already present with persistent albuminuria shows SGLT2 and monitoring logic."
    ),
    "sparse_realistic_pcp_intake": (
        "Standard primary-care intake data with advanced prevention clarifiers still missing."
    ),
    "younger_strong_family_history": (
        "Low short-term ASCVD risk, but early metabolic signals and premature "
        "family history create a prevention opportunity."
    ),
    "older_multiple_treated_risk_factors": (
        "Older patient with treated diabetes, BP, and lipids to show multi-domain prevention."
    ),
    "rheumatoid_arthritis_risk_enhancer": (
        "Rheumatoid arthritis adds inflammatory risk context to otherwise borderline prevention data."
    ),
    "south_asian_ancestry_context": (
        "South Asian ancestry and metabolic signals personalize risk without making ancestry a diagnosis."
    ),
    "active_smoker_prevention": (
        "Active smoking shifts prevention priorities while keeping aspirin and medication logic separated."
    ),
    "cancer_survivor_context": (
        "Cancer survivorship appears as context while lipid decisions remain driven by ASCVD risk."
    ),
    "multiple_enhancers_missing_apob_lpa": (
        "Multiple enhancers with missing ApoB/Lp(a)/UACR shows data-completion value."
    ),
}


DEMO_CATEGORIES = (
    "Foundational prevention",
    "Atherogenic burden",
    "Plaque and imaging",
    "CKM / kidney / metabolic",
    "Treatment-state cases",
    "Special risk enhancers",
)


DEMO_CASE_METADATA = {
    "healthy_low_risk_prevention": {
        "category": "Foundational prevention",
        "expected_showcase_points": ("low-risk complete data", "lifestyle prevention"),
        "expected_primary_action": "Lifestyle-focused prevention.",
        "expected_level_or_level_range": "Level 1",
        "expected_risk_framing": "Low short-term ASCVD risk with complete reassuring baseline data.",
    },
    "borderline_ascvd_discussion": {
        "category": "Foundational prevention",
        "expected_showcase_points": ("borderline ASCVD risk", "ApoB"),
        "expected_primary_action": "Moderate-intensity statin discussion if risk enhancers support treatment.",
        "expected_level_or_level_range": "Level 3A-3B",
        "expected_risk_framing": "Borderline ASCVD risk discussion.",
    },
    "low_10y_elevated_30y": {
        "category": "Foundational prevention",
        "expected_showcase_points": ("low 10-year high 30-year", "prevention opportunity"),
        "expected_primary_action": "Prevention intensity and shared decision-making.",
        "expected_level_or_level_range": "Level 3A-3B",
        "expected_risk_framing": "Low short-term risk with elevated longer-term ASCVD risk.",
    },
    "younger_strong_family_history": {
        "category": "Foundational prevention",
        "expected_showcase_points": ("premature family history", "prevention opportunity"),
        "expected_primary_action": "Early prevention discussion.",
        "expected_level_or_level_range": "Level 3B",
        "expected_risk_framing": "Low short-term ASCVD risk but elevated lifetime concern.",
    },
    "obesity_metabolic_syndrome": {
        "category": "Foundational prevention",
        "expected_showcase_points": ("metabolic risk", "missing-data clarification"),
        "expected_primary_action": "Lifestyle and data completion.",
        "expected_level_or_level_range": "Level 2-3",
        "expected_risk_framing": "Metabolic risk without measured plaque.",
    },
    "prediabetes_insulin_resistance": {
        "category": "CKM / kidney / metabolic",
        "expected_showcase_points": ("prediabetes", "reproductive history"),
        "expected_primary_action": "Metabolic prevention.",
        "expected_level_or_level_range": "Level 2-3",
        "expected_risk_framing": "Prediabetes and insulin-resistance prevention.",
    },
    "high_apob_discordance": {
        "category": "Atherogenic burden",
        "expected_showcase_points": ("ApoB discordance", "particle burden", "premature family history"),
        "expected_primary_action": "Discuss moderate-intensity statin.",
        "expected_level_or_level_range": "Level 3",
        "expected_risk_framing": "Low 10-year risk with elevated ApoB and family-history context.",
    },
    "ldl_high_apob_missing": {
        "category": "Atherogenic burden",
        "expected_showcase_points": ("LDL-C", "missing-data clarification"),
        "expected_primary_action": "Measure ApoB and discuss lipid lowering.",
        "expected_level_or_level_range": "Level 3",
        "expected_risk_framing": "LDL-C burden with ApoB missing.",
    },
    "ldl_severe_hypercholesterolemia_demo": {
        "category": "Atherogenic burden",
        "expected_showcase_points": ("LDL-C >=190", "FH pathway"),
        "expected_primary_action": "High-intensity statin pathway.",
        "expected_level_or_level_range": "Level 3B",
        "expected_risk_framing": "Severe hypercholesterolemia pathway; CAC 0 does not de-risk.",
    },
    "elevated_lpa": {
        "category": "Atherogenic burden",
        "expected_showcase_points": ("Lp(a)", "risk-enhancer context"),
        "expected_primary_action": "LDL/ApoB prevention discussion.",
        "expected_level_or_level_range": "Level 2-3",
        "expected_risk_framing": "Lp(a) risk-enhancer context.",
    },
    "hypertriglyceridemia_insulin_resistance": {
        "category": "Atherogenic burden",
        "expected_showcase_points": ("hypertriglyceridemia", "metabolic risk"),
        "expected_primary_action": "Metabolic and triglyceride risk reduction.",
        "expected_level_or_level_range": "Level 3",
        "expected_risk_framing": "Insulin-resistance and remnant-risk pattern.",
    },
    "cac_zero_ambiguity_resolution": {
        "category": "Plaque and imaging",
        "expected_showcase_points": ("CAC 0", "plaque clarification"),
        "expected_primary_action": "Conservative plaque-informed discussion.",
        "expected_level_or_level_range": "Level 2-3",
        "expected_risk_framing": "CAC 0 lowers detected plaque concern.",
    },
    "cac_1_99_plaque_present": {
        "category": "Plaque and imaging",
        "expected_showcase_points": ("CAC 1-99", "plaque-present pathway"),
        "expected_primary_action": "Plaque-informed statin discussion.",
        "expected_level_or_level_range": "Level 4",
        "expected_risk_framing": "Mild plaque present.",
    },
    "cac_100_high_plaque_burden": {
        "category": "Plaque and imaging",
        "expected_showcase_points": ("CAC >=100", "treatment escalation"),
        "expected_primary_action": "Plaque-driven lipid lowering.",
        "expected_level_or_level_range": "Level 4-5",
        "expected_risk_framing": "Moderate/high plaque burden clarifies treatment intensity.",
    },
    "cac_300_high_plaque_burden": {
        "category": "Plaque and imaging",
        "expected_showcase_points": ("CAC high burden", "treatment escalation"),
        "expected_primary_action": "High-intensity lipid-lowering pathway.",
        "expected_level_or_level_range": "Level 5",
        "expected_risk_framing": "High plaque burden dominates interpretation.",
    },
    "incidental_cac_on_ct": {
        "category": "Plaque and imaging",
        "expected_showcase_points": ("incidental CAC", "plaque clarification"),
        "expected_primary_action": "Qualitative plaque context and CAC clarification if needed.",
        "expected_level_or_level_range": "Level 4",
        "expected_risk_framing": "Incidental coronary calcium without numeric Agatston score.",
    },
    "breast_arterial_calcification_demo": {
        "category": "Plaque and imaging",
        "expected_showcase_points": ("breast arterial calcification", "risk-enhancer context"),
        "expected_primary_action": "Contextual vascular-risk review.",
        "expected_level_or_level_range": "Level 2-3",
        "expected_risk_framing": "Non-coronary vascular calcification context.",
    },
    "diabetes_without_kidney_disease": {
        "category": "CKM / kidney / metabolic",
        "expected_showcase_points": ("diabetes", "CKM staging"),
        "expected_primary_action": "Diabetes-driven lipid and glycemic prevention.",
        "expected_level_or_level_range": "Level 3",
        "expected_risk_framing": "Diabetes without kidney involvement.",
    },
    "diabetes_ckm_stage": {
        "category": "CKM / kidney / metabolic",
        "expected_showcase_points": ("diabetes", "CKM staging"),
        "expected_primary_action": "Kidney, glycemic, and lipid prevention.",
        "expected_level_or_level_range": "Level 3B",
        "expected_risk_framing": "Diabetes with albuminuria/CKM stage.",
    },
    "ckd_albuminuria": {
        "category": "CKM / kidney / metabolic",
        "expected_showcase_points": ("albuminuria", "kidney involvement"),
        "expected_primary_action": "Statin, BP, ACEi/ARB, and kidney protection.",
        "expected_level_or_level_range": "Level 3B",
        "expected_risk_framing": "Albuminuria-mediated kidney and ASCVD risk.",
    },
    "ckd_g3a_a2": {
        "category": "CKM / kidney / metabolic",
        "expected_showcase_points": ("CKD G3aA2", "kidney involvement"),
        "expected_primary_action": "Kidney-protective and lipid-prevention discussion.",
        "expected_level_or_level_range": "Level 3B",
        "expected_risk_framing": "Reduced eGFR plus albuminuria.",
    },
    "higher_albuminuria_sglt2_consideration": {
        "category": "CKM / kidney / metabolic",
        "expected_showcase_points": ("SGLT2", "albuminuria"),
        "expected_primary_action": "SGLT2 and kidney-protective therapy consideration.",
        "expected_level_or_level_range": "Level 3B-5",
        "expected_risk_framing": "Higher albuminuria with diabetes and CKD.",
    },
    "on_treatment_above_target_lipids": {
        "category": "Treatment-state cases",
        "expected_showcase_points": ("on-treatment residual risk", "statin intolerance"),
        "expected_primary_action": "Continue therapy and consider intensification/add-on.",
        "expected_level_or_level_range": "Level 4-5",
        "expected_risk_framing": "Above target on therapy with plaque.",
    },
    "high_intensity_add_on_discussion": {
        "category": "Treatment-state cases",
        "expected_showcase_points": ("add-on therapy", "CAC high burden"),
        "expected_primary_action": "Consider add-on LDL/ApoB lowering.",
        "expected_level_or_level_range": "Level 5",
        "expected_risk_framing": "High plaque burden despite high-intensity statin.",
    },
    "severe_secondary_prevention": {
        "category": "Treatment-state cases",
        "expected_showcase_points": ("secondary prevention", "very-high-risk ASCVD targets", "add-on therapy"),
        "expected_primary_action": "Intensify secondary-prevention lipid-lowering therapy.",
        "expected_level_or_level_range": "Level 5",
        "expected_risk_framing": "Established ASCVD with multiple very-high-risk features.",
    },
    "statin_intolerance_demo": {
        "category": "Treatment-state cases",
        "expected_showcase_points": ("statin intolerance", "plaque-present pathway"),
        "expected_primary_action": "Maximally tolerated lipid-lowering strategy.",
        "expected_level_or_level_range": "Level 4",
        "expected_risk_framing": "Plaque and ApoB burden with statin intolerance.",
    },
    "bp_treated_above_kidney_goal": {
        "category": "Treatment-state cases",
        "expected_showcase_points": ("BP treated above goal", "albuminuria"),
        "expected_primary_action": "Treat BP toward kidney goal.",
        "expected_level_or_level_range": "Level 3B",
        "expected_risk_framing": "Albuminuria makes BP target central.",
    },
    "ace_arb_persistent_albuminuria": {
        "category": "Treatment-state cases",
        "expected_showcase_points": ("ACEi/ARB", "SGLT2"),
        "expected_primary_action": "Continue ACEi/ARB and consider SGLT2.",
        "expected_level_or_level_range": "Level 3B",
        "expected_risk_framing": "Persistent albuminuria despite kidney-protective therapy.",
    },
    "rheumatoid_arthritis_risk_enhancer": {
        "category": "Special risk enhancers",
        "expected_showcase_points": ("rheumatoid arthritis", "risk-enhancer context"),
        "expected_primary_action": "Personalized risk discussion.",
        "expected_level_or_level_range": "Level 2-3",
        "expected_risk_framing": "Inflammatory risk enhancer.",
    },
    "south_asian_ancestry_context": {
        "category": "Special risk enhancers",
        "expected_showcase_points": ("South Asian ancestry", "metabolic risk"),
        "expected_primary_action": "Personalized prevention discussion.",
        "expected_level_or_level_range": "Level 2-3",
        "expected_risk_framing": "Ancestry context plus metabolic signals.",
    },
    "active_smoker_prevention": {
        "category": "Special risk enhancers",
        "expected_showcase_points": ("active smoking", "risk-enhancer context"),
        "expected_primary_action": "Smoking cessation and ASCVD prevention.",
        "expected_level_or_level_range": "Level 3",
        "expected_risk_framing": "Smoking as a major modifiable driver.",
    },
    "cancer_survivor_context": {
        "category": "Special risk enhancers",
        "expected_showcase_points": ("cancer survivor", "risk-enhancer context"),
        "expected_primary_action": "Contextual prevention review.",
        "expected_level_or_level_range": "Level 2-3",
        "expected_risk_framing": "Cancer survivorship as context only.",
    },
    "multiple_enhancers_missing_apob_lpa": {
        "category": "Special risk enhancers",
        "expected_showcase_points": ("missing-data clarification", "multiple enhancers"),
        "expected_primary_action": "Complete ApoB/Lp(a)/UACR and discuss prevention.",
        "expected_level_or_level_range": "Level 3",
        "expected_risk_framing": "Multiple enhancers with key data gaps.",
    },
    "sparse_realistic_pcp_intake": {
        "category": "Special risk enhancers",
        "expected_showcase_points": ("missing-data clarification", "PCP intake"),
        "expected_primary_action": "Complete advanced prevention data.",
        "expected_level_or_level_range": "Level 2-3",
        "expected_risk_framing": "Believable PCP intake with advanced missingness.",
    },
    "older_multiple_treated_risk_factors": {
        "category": "Treatment-state cases",
        "expected_showcase_points": ("treated risk factors", "multi-domain prevention"),
        "expected_primary_action": "Continue and reassess multi-domain prevention.",
        "expected_level_or_level_range": "Level 3",
        "expected_risk_framing": "Older treated diabetes/BP/lipids.",
    },
}


def _golden_cases_path() -> Path:
    return Path(__file__).resolve().parents[1] / "tests" / "golden_cases" / "golden_cases.json"


def demo_patient_payloads() -> dict[str, dict]:
    """Return the in-app demo payloads with realistic primary-care baselines."""
    return deepcopy(DEMO_PATIENTS)


def load_golden_case_patients(path: Path | None = None) -> dict[str, dict]:
    """Load patient payloads from the golden-case fixture file."""
    fixture_path = path or _golden_cases_path()
    with fixture_path.open(encoding="utf-8") as handle:
        cases = json.load(handle)
    return {
        str(case.get("name")): dict(case.get("patient") or {})
        for case in cases
        if case.get("name") and case.get("patient")
    }


def demo_case_options(patients_by_case: dict[str, dict] | None = None) -> list[tuple[str, str]]:
    """Return friendly demo labels paired with available demo case names."""
    available = patients_by_case if patients_by_case is not None else DEMO_PATIENTS
    return [(label, case_name) for label, case_name in DEMO_CASES if case_name in available]


def demo_case_category(case_name: str) -> str:
    """Return the curated demo category for a case."""
    return DEMO_CASE_METADATA.get(case_name, {}).get("category", "Other")


def demo_case_options_by_category(
    category: str | None = None,
    patients_by_case: dict[str, dict] | None = None,
) -> list[tuple[str, str]]:
    """Return demo options filtered by category while preserving curated order."""
    options = demo_case_options(patients_by_case)
    if not category or category == "All":
        return options
    return [
        (label, case_name)
        for label, case_name in options
        if demo_case_category(case_name) == category
    ]


def demo_case_description(case_name: str) -> str:
    """Return a short clinician-facing selector description for a demo case."""
    return DEMO_CASE_DESCRIPTIONS.get(case_name, "")


def demo_case_metadata(case_name: str) -> dict:
    """Return defensive-copy metadata for demo audit and selector details."""
    return deepcopy(DEMO_CASE_METADATA.get(case_name, {}))


def build_demo_patient(case_name: str, patients_by_case: dict[str, dict] | None = None):
    """Build a Patient object from a named demo payload."""
    available = patients_by_case if patients_by_case is not None else DEMO_PATIENTS
    if case_name not in available:
        raise KeyError(f"Unknown demo case: {case_name}")
    return build_patient_from_inputs(available[case_name])
