import json
from copy import deepcopy
from pathlib import Path

from ui.input_worksheet import build_patient_from_inputs


DEMO_CASES = (
    ("Healthy low-risk prevention", "healthy_low_risk_prevention"),
    ("Obesity / metabolic syndrome", "obesity_metabolic_syndrome"),
    ("Prediabetes / insulin resistance", "prediabetes_insulin_resistance"),
    ("High ApoB discordance", "high_apob_discordance"),
    ("Elevated Lp(a)", "elevated_lpa"),
    ("CAC 0 ambiguity resolution", "cac_zero_ambiguity_resolution"),
    ("CAC 1-99 plaque present", "cac_1_99_plaque_present"),
    ("CAC >=100 high plaque burden", "cac_100_high_plaque_burden"),
    ("CKD / albuminuria", "ckd_albuminuria"),
    ("Diabetes + CKM stage", "diabetes_ckm_stage"),
    ("On-treatment above-target lipids", "on_treatment_above_target_lipids"),
    ("Sparse but realistic PCP intake", "sparse_realistic_pcp_intake"),
    ("Younger patient with premature family history", "younger_strong_family_history"),
    ("Older multiple treated risk factors", "older_multiple_treated_risk_factors"),
)


DEMO_PATIENTS = {
    "healthy_low_risk_prevention": {
        "age": 34,
        "sex": "female",
        "height_in": 65,
        "weight_lb": 132,
        "bmi": 22.0,
        "sbp": 108,
        "dbp": 68,
        "bp_treated": False,
        "tc": 168,
        "ldl_c": 88,
        "hdl_c": 62,
        "triglycerides": 88,
        "apob": 70,
        "lp_a_value": 18,
        "lp_a_unit": "nmol/L",
        "a1c": 5.2,
        "diabetes": False,
        "egfr": 105,
        "creatinine": 0.78,
        "uacr": 4,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "none",
    },
    "obesity_metabolic_syndrome": {
        "age": 48,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 235,
        "bmi": 33.7,
        "sbp": 136,
        "dbp": 86,
        "bp_treated": False,
        "tc": 212,
        "ldl_c": 132,
        "hdl_c": 39,
        "triglycerides": 205,
        "apob": 108,
        "lp_a_value": 36,
        "lp_a_unit": "nmol/L",
        "a1c": 5.6,
        "diabetes": False,
        "egfr": 92,
        "creatinine": 1.0,
        "uacr": None,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "osa": True,
        "masld": True,
        "medications_raw": "none",
    },
    "prediabetes_insulin_resistance": {
        "age": 52,
        "sex": "female",
        "height_in": 64,
        "weight_lb": 184,
        "bmi": 31.6,
        "sbp": 128,
        "dbp": 78,
        "bp_treated": False,
        "tc": 198,
        "ldl_c": 122,
        "hdl_c": 46,
        "triglycerides": 168,
        "apob": 92,
        "lp_a_value": 40,
        "lp_a_unit": "nmol/L",
        "a1c": 6.1,
        "diabetes": False,
        "egfr": 88,
        "creatinine": 0.86,
        "uacr": 12,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "gestational_diabetes": True,
        "medications_raw": "vitamin D",
    },
    "high_apob_discordance": {
        "age": 55,
        "sex": "male",
        "height_in": 69,
        "weight_lb": 190,
        "bmi": 28.1,
        "sbp": 126,
        "dbp": 76,
        "bp_treated": False,
        "tc": 190,
        "ldl_c": 108,
        "hdl_c": 48,
        "triglycerides": 170,
        "apob": 125,
        "lp_a_value": 30,
        "lp_a_unit": "nmol/L",
        "a1c": 5.5,
        "diabetes": False,
        "egfr": 90,
        "creatinine": 0.98,
        "uacr": 8,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "none",
    },
    "elevated_lpa": {
        "age": 46,
        "sex": "female",
        "height_in": 66,
        "weight_lb": 150,
        "bmi": 24.2,
        "sbp": 118,
        "dbp": 72,
        "bp_treated": False,
        "tc": 190,
        "ldl_c": 124,
        "hdl_c": 56,
        "triglycerides": 90,
        "apob": 86,
        "lp_a_value": 188,
        "lp_a_unit": "nmol/L",
        "a1c": 5.3,
        "diabetes": False,
        "egfr": 98,
        "creatinine": 0.76,
        "uacr": 5,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "preeclampsia": True,
        "medications_raw": "levothyroxine",
    },
    "cac_zero_ambiguity_resolution": {
        "age": 58,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 207,
        "bmi": 29.7,
        "sbp": 134,
        "dbp": 82,
        "bp_treated": True,
        "tc": 215,
        "ldl_c": 142,
        "hdl_c": 44,
        "triglycerides": 146,
        "apob": 105,
        "lp_a_value": None,
        "lp_a_unit": "nmol/L",
        "a1c": 5.7,
        "diabetes": False,
        "egfr": 86,
        "creatinine": 0.94,
        "uacr": 10,
        "cac": 0,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "lisinopril 10 mg daily",
        "ace_arb": True,
    },
    "cac_1_99_plaque_present": {
        "age": 62,
        "sex": "female",
        "height_in": 64,
        "weight_lb": 172,
        "bmi": 29.5,
        "sbp": 132,
        "dbp": 78,
        "bp_treated": True,
        "tc": 205,
        "ldl_c": 128,
        "hdl_c": 52,
        "triglycerides": 125,
        "apob": 95,
        "lp_a_value": 82,
        "lp_a_unit": "nmol/L",
        "a1c": 5.8,
        "diabetes": False,
        "egfr": 82,
        "creatinine": 0.88,
        "uacr": 9,
        "cac": 38,
        "cac_percentile": 82,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "amlodipine 5 mg daily; hydrochlorothiazide 12.5 mg daily",
    },
    "cac_100_high_plaque_burden": {
        "age": 61,
        "sex": "female",
        "height_in": 65,
        "weight_lb": 176,
        "bmi": 29.3,
        "sbp": 138,
        "dbp": 84,
        "bp_treated": True,
        "tc": 218,
        "ldl_c": 124,
        "hdl_c": 56,
        "triglycerides": 190,
        "apob": 112,
        "lp_a_value": 238,
        "lp_a_unit": "nmol/L",
        "a1c": 5.9,
        "diabetes": False,
        "egfr": 78,
        "creatinine": 0.9,
        "uacr": 14,
        "cac": 350,
        "cac_percentile": 91,
        "smoker": False,
        "family_history_premature_ascvd": True,
        "family_history_relationship": "father",
        "family_history_event_type": "MI",
        "family_history_age_at_event": 54,
        "medications_raw": "losartan 50 mg daily",
        "ace_arb": True,
    },
    "ckd_albuminuria": {
        "age": 57,
        "sex": "male",
        "height_in": 68,
        "weight_lb": 204,
        "bmi": 31.0,
        "sbp": 142,
        "dbp": 86,
        "bp_treated": True,
        "tc": 202,
        "ldl_c": 126,
        "hdl_c": 46,
        "triglycerides": 150,
        "apob": 96,
        "lp_a_value": 65,
        "lp_a_unit": "nmol/L",
        "a1c": 6.0,
        "diabetes": False,
        "egfr": 64,
        "creatinine": 1.25,
        "uacr": 48,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "losartan 100 mg daily; chlorthalidone 12.5 mg daily",
        "ace_arb": True,
    },
    "diabetes_ckm_stage": {
        "age": 60,
        "sex": "female",
        "height_in": 63,
        "weight_lb": 186,
        "bmi": 32.9,
        "sbp": 136,
        "dbp": 80,
        "bp_treated": True,
        "tc": 210,
        "ldl_c": 132,
        "hdl_c": 43,
        "triglycerides": 176,
        "apob": 110,
        "lp_a_value": 42,
        "lp_a_unit": "nmol/L",
        "a1c": 7.4,
        "diabetes": True,
        "diabetes_duration_years": 8,
        "egfr": 52,
        "creatinine": 1.15,
        "uacr": 210,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "metformin 1000 mg twice daily; lisinopril 20 mg daily",
        "dm_meds_raw": "metformin",
        "ace_arb": True,
    },
    "on_treatment_above_target_lipids": {
        "age": 61,
        "sex": "female",
        "height_in": 65,
        "weight_lb": 173,
        "bmi": 28.8,
        "sbp": 124,
        "dbp": 76,
        "bp_treated": True,
        "tc": 218,
        "ldl_c": 124,
        "hdl_c": 56,
        "triglycerides": 190,
        "apob": 112,
        "lp_a_value": 238,
        "lp_a_unit": "nmol/L",
        "a1c": 5.8,
        "diabetes": False,
        "egfr": 76,
        "creatinine": 0.92,
        "uacr": 11,
        "cac": 145,
        "cac_percentile": 78,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "lipid_lowering": True,
        "statin_intensity": "moderate",
        "statin_intolerance": True,
        "medications_raw": "pravastatin 40 mg daily; ezetimibe 10 mg daily; prior atorvastatin and rosuvastatin myalgias",
    },
    "sparse_realistic_pcp_intake": {
        "age": 49,
        "sex": "male",
        "height_in": 71,
        "weight_lb": 198,
        "bmi": 27.6,
        "sbp": 128,
        "dbp": 80,
        "bp_treated": False,
        "tc": 214,
        "ldl_c": 136,
        "hdl_c": 45,
        "triglycerides": 165,
        "a1c": None,
        "diabetes": False,
        "egfr": 96,
        "creatinine": 1.0,
        "uacr": None,
        "apob": None,
        "lp_a_value": None,
        "lp_a_unit": "nmol/L",
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "medications_raw": "none",
    },
    "younger_strong_family_history": {
        "age": 38,
        "sex": "male",
        "height_in": 70,
        "weight_lb": 205,
        "bmi": 29.4,
        "sbp": 124,
        "dbp": 78,
        "bp_treated": False,
        "tc": 236,
        "ldl_c": 164,
        "hdl_c": 48,
        "triglycerides": 186,
        "apob": 118,
        "lp_a_value": 96,
        "lp_a_unit": "nmol/L",
        "a1c": 5.9,
        "diabetes": False,
        "egfr": 100,
        "creatinine": 0.9,
        "uacr": 9,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": True,
        "family_history_relationship": "father",
        "family_history_event_type": "MI",
        "family_history_age_at_event": 49,
        "medications_raw": "none",
    },
    "older_multiple_treated_risk_factors": {
        "age": 72,
        "sex": "female",
        "height_in": 62,
        "weight_lb": 178,
        "bmi": 32.6,
        "sbp": 132,
        "dbp": 74,
        "bp_treated": True,
        "tc": 176,
        "ldl_c": 92,
        "hdl_c": 50,
        "triglycerides": 170,
        "apob": 88,
        "lp_a_value": 30,
        "lp_a_unit": "nmol/L",
        "a1c": 7.0,
        "diabetes": True,
        "diabetes_duration_years": 6,
        "egfr": 68,
        "creatinine": 0.98,
        "uacr": 22,
        "cac_not_done": True,
        "smoker": False,
        "family_history_premature_ascvd": False,
        "lipid_lowering": True,
        "statin_intensity": "moderate",
        "sglt2": True,
        "ace_arb": True,
        "medications_raw": "atorvastatin 20 mg daily; metformin; empagliflozin; losartan 50 mg daily",
        "dm_meds_raw": "metformin; empagliflozin",
    },
}


DEMO_CASE_DESCRIPTIONS = {
    "healthy_low_risk_prevention": (
        "Complete reassuring baseline data with low ASCVD risk and lifestyle-focused prevention."
    ),
    "obesity_metabolic_syndrome": (
        "Obesity, OSA/MASLD context, and triglyceride burden with advanced clarifiers still open."
    ),
    "prediabetes_insulin_resistance": (
        "Prediabetes and insulin-resistance pattern with reproductive history context."
    ),
    "high_apob_discordance": (
        "ApoB is high despite only modest LDL-C, highlighting particle-burden discordance."
    ),
    "elevated_lpa": (
        "Low near-term risk with elevated Lp(a) and reproductive risk context."
    ),
    "cac_zero_ambiguity_resolution": (
        "CAC 0 helps frame plaque burden while cardiometabolic signals remain visible."
    ),
    "cac_1_99_plaque_present": (
        "Mild measured coronary calcium demonstrates the plaque-present pathway."
    ),
    "cac_100_high_plaque_burden": (
        "High CAC burden with Lp(a), BP treatment, and above-target atherogenic burden."
    ),
    "ckd_albuminuria": (
        "Albuminuria and treated BP show early kidney-risk interpretation."
    ),
    "diabetes_ckm_stage": (
        "Diabetes with CKM/kidney involvement and treatment-forward prevention needs."
    ),
    "on_treatment_above_target_lipids": (
        "Already on lipid therapy but above CAC-driven targets with prior statin intolerance."
    ),
    "sparse_realistic_pcp_intake": (
        "Standard primary-care intake data with advanced prevention clarifiers still missing."
    ),
    "younger_strong_family_history": (
        "Low short-term ASCVD risk, but early metabolic signals and premature "
        "family history create a prevention opportunity."
    ),
    "older_multiple_treated_risk_factors": (
        "Older patient with treated diabetes, BP, and lipids to show multi-domain prevention."
    ),
}


def _golden_cases_path() -> Path:
    return Path(__file__).resolve().parents[1] / "tests" / "golden_cases" / "golden_cases.json"


def demo_patient_payloads() -> dict[str, dict]:
    """Return the in-app demo payloads with realistic primary-care baselines."""
    return deepcopy(DEMO_PATIENTS)


def load_golden_case_patients(path: Path | None = None) -> dict[str, dict]:
    """Load patient payloads from the golden-case fixture file."""
    fixture_path = path or _golden_cases_path()
    with fixture_path.open(encoding="utf-8") as handle:
        cases = json.load(handle)
    return {
        str(case.get("name")): dict(case.get("patient") or {})
        for case in cases
        if case.get("name") and case.get("patient")
    }


def demo_case_options(patients_by_case: dict[str, dict] | None = None) -> list[tuple[str, str]]:
    """Return friendly demo labels paired with available demo case names."""
    available = patients_by_case if patients_by_case is not None else DEMO_PATIENTS
    return [(label, case_name) for label, case_name in DEMO_CASES if case_name in available]


def demo_case_description(case_name: str) -> str:
    """Return a short clinician-facing selector description for a demo case."""
    return DEMO_CASE_DESCRIPTIONS.get(case_name, "")


def build_demo_patient(case_name: str, patients_by_case: dict[str, dict] | None = None):
    """Build a Patient object from a named demo payload."""
    available = patients_by_case if patients_by_case is not None else DEMO_PATIENTS
    if case_name not in available:
        raise KeyError(f"Unknown demo case: {case_name}")
    return build_patient_from_inputs(available[case_name])
